USE [SALES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ManageSalesStaffs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MyLoginID] [varchar](20) NOT NULL DEFAULT (''),
	[MyStaffID] [varchar](20) NOT NULL DEFAULT (''),
	[UpdDate] [datetime] NOT NULL DEFAULT (getdate()),
	[UserID] [varchar](30) NOT NULL DEFAULT (suser_sname()),
 CONSTRAINT [PK_ManageSalesStaffs] PRIMARY KEY CLUSTERED 
(
	[MyLoginID] ASC,
	[MyStaffID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO ManageSalesStaffs VALUES('0810','0811',GETDATE(),'0807')
INSERT INTO ManageSalesStaffs VALUES('0810','0812',GETDATE(),'0807')
INSERT INTO ManageSalesStaffs VALUES('0813','0814',GETDATE(),'0807')

