USE [SALES]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ItemsMaster](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ItemName] [varchar](100) NOT NULL DEFAULT (''),
	[UpdDate] [datetime] NOT NULL DEFAULT (getdate()),
	[UserID] [varchar](30) NOT NULL DEFAULT (suser_sname()),
 CONSTRAINT [PK_ItemsMaster] PRIMARY KEY CLUSTERED 
(
	[ItemName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO ItemsMaster VALUES('Dell XPS 13 Plus',GETDATE(),'0807')
INSERT INTO ItemsMaster VALUES('HP Spectre x360 135',GETDATE(),'0807')
INSERT INTO ItemsMaster VALUES('Inspiron 15 Laptop 9x',GETDATE(),'0807')

