USE [SALES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserMaster](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LoginStaffID] [varchar](20) NOT NULL DEFAULT (''),
	[Pwd] [varchar](max) NOT NULL DEFAULT (''),
	[StaffName] [varchar](500) NOT NULL DEFAULT (''),
	[Role] [varchar](20) NOT NULL DEFAULT (''),
	[UpdDate] [datetime] NOT NULL DEFAULT (getdate()),
	[UserID] [varchar](30) NOT NULL DEFAULT (suser_sname()),
 CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED 
(
	[LoginStaffID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO UserMaster VALUES('0807','EmVBUhMEmwILnSq4B6OGoQ==','SUMATHAN ZOOSHAN','ADMIN',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0810','EmVBUhMEmwJHECCSi3JVmA==','KOO YONG CHIAN','MANAGER',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0811','EmVBUhMEmwL21gLqixoXxg==','CHANG YOONG MIN','SALES',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0812','EmVBUhMEmwKfqVMK8XQ23w==','HO CHIAN MUN','SALES',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0813','EmVBUhMEmwJTu1kW1RadJA==','BBMAN','MANAGER',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0814','EmVBUhMEmwLgvPfoZjR73A==','MOHD BIN LADEN','SALES',GETDATE(),'0807')
INSERT INTO UserMaster VALUES('0815','EmVBUhMEmwJlURNIQmhNxw==','WEE KER LI','SALES',GETDATE(),'0807')

--password id is same with login id


